@startuml
scale 900 width

'CANCEL --> 取消
'UNTREATED --> 未处理
'TREATED --> 已处理
'STATION --> 已分配配送站
'CONVERT --> 已转换
'INLINE --> 生产中
'DELIVERY --> 已分配配送员
'COMPLETED --> 订单完成
'EXCEPTION --> 订单异常

state 扒单 {
}

state 系统下单 {
}

state 未处理 {
}

state 已处理 {
}

state 订单完成 {
}

state 订单异常 {
}

state 订单取消{
}

state 已分配配送站 {
}

state 已转换 {
}

state 生产中 {
}

state 已分配配送员 {
}

扒单 --> 未处理
系统下单 --> 已处理 : 保存

未处理 --> 已处理 : 保存
未处理 --> 已分配配送站 : 提交
未处理 --> 订单取消 : 取消

已处理 --> 已处理 : 保存
已处理 --> 已分配配送站 : 提交
已处理 --> 订单取消 : 取消

已分配配送站 --> 已转换 : 转换
已分配配送站 --> 已分配配送站 : 修改配送站/地址
已分配配送站 --> 订单取消 : 取消

已转换 --> 生产中 : 打印
已转换 --> 已分配配送站 : 修改配送站/地址
已转换 --> 订单取消 : 取消

生产中 --> 已分配配送员 : 分配配送员
生产中 --> 已转换 : 申请重打印审核通过
生产中 --> 订单异常 : 取消

已分配配送员 --> 已分配配送员 : 转给其它配送员
已分配配送员 --> 订单完成 : 签收
已分配配送员 --> 订单异常 : 拒收

订单完成 --> 订单完成 : 编辑配送员

@enduml