@startuml
scale 350 width

state 未审核 {
}

state 已审核 {
}

state 退款完成 {
}

state 退款取消 {
}

[*] --> 未审核 : 申请退款
未审核 --> 未审核 : 编辑
未审核 --> 已审核 : 审核通过
未审核 --> 退款取消 : 退款取消

已审核 --> 未审核 : 编辑
已审核 --> 退款取消 : 退款取消
已审核 --> 退款完成 : 退款完成

@enduml