@startuml
scale 400 width

state 未审核 {
}

state 已审核 {
}

state 退款完成 {
}

state 退款取消 {
}

[*] --> 未确认 : 客户提交申请

未确认 --> 未审核 : 客服确认

[*] --> 未审核 : 客服申请退款
未审核 --> 未审核 : 编辑
未审核 --> 已审核 : 审核通过
未审核 --> 退款取消 : 退款取消

已审核 --> 未审核 : 编辑
已审核 --> 退款取消 : 退款取消
已审核 --> 退款完成 : 退款完成

@enduml